name: PR Validation

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Build affected 
        run: nx affected -t build

      - name: Run unit test
        run: nx affected -t test

      - name: Run lint
        run: nx affected -t lint


      - name: Run end-to-end tests
        run: nx e2e gull-e2e
