name: PR Validation

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: nx build demoapp

      - name: Run unit tests for components library
        run: nx test components

      - name: Run unit tests for page1 library
        run: nx test page1

      - name: Run end-to-end tests
        run: nx e2e gull-e2e
