name: PR Validation

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Lint affected 
        run: npx nx affected --target=lint

      - name: Test affected 
        run: npx nx affected --target=test

      - name: Build affected 
        run: npx nx affected --target=build


      - name: Run end-to-end tests
        run: nx e2e gull-e2e
